---
deployment:
  tasks:
    - /usr/local/bin/ea-php84 composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/ea-php84 /home/undfqhne/public_html/new.racerhistory.com/bin/cake.php migrations migrate --no-ansi
    - /usr/local/bin/ea-php84 /home/undfqhne/public_html/new.racerhistory.com/bin/cake.php cache clear_all
