---
deployment:
  tasks:
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - php bin/cake.php migrations migrate --no-ansi
    - php bin/cake.php cache clear_all
