coverage:
  status:
    project:
      php:
        target: 98
      js:
        target: 88
      branches:
        target: 80

comment:
  layout: 'header, diff, flags, files'
  behavior: default
  require_changes: false

ignore:
  - 'tests/'
  - 'js/tests/'
  - 'vendor/'
  - 'tmp/'
  - 'logs/'
  - 'config/Migrations/'

flag_management:
  default_rules:
    carryforward: true

flags:
  unittests:
    paths:
      - src/
    carryforward: true
  jstests:
    paths:
      - js/
    carryforward: true
