coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 10%

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "vendor/"
  - "tmp/"
  - "logs/"
  - "config/Migrations/"
  - "webroot/"

flag_management:
  default_rules:
    carryforward: true

flags:
  unittests:
    paths:
      - src/
    carryforward: true
