/* eslint-env node */
// @ts-check

const eslint = require("@eslint/js");

module.exports = [
    eslint.configs.recommended,
    {
        // Ignore third-party libraries, config and vendor files
        ignores: [
            "eslint.config.cjs",
            "jest.setup.js",
            "playwright.config.js",
            "convert-tests-to-esm.mjs",
            "webroot/js/tinymce/**",
            "vendor/**",
            "node_modules/**",
            "tmp/**",
            "logs/**",
            "coverage-js/**",
            "playwright-report/**",
            "test-results/**",
        ],
    },
    {
        files: ["js/**/*.js", "js/**/*.mjs"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                navigator: "readonly",
                fetch: "readonly",
                alert: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                Event: "readonly",
                HTMLImageElement: "readonly",
                FileReader: "readonly",
                FormData: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
            },
        },
    },
    {
        files: ["js/legacy/**/*.js"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                $: "readonly",
                jQuery: "readonly",
                DataTable: "readonly",
                alert: "readonly",
                confirm: "readonly",
                fetch: "readonly",
                setTimeout: "readonly",
                FormData: "readonly",
                Blob: "readonly",
                File: "readonly",
                bootstrap: "readonly",
                Event: "readonly",
                URLSearchParams: "readonly",
                FileReader: "readonly",
                Cropper: "readonly",
                module: "readonly",
            },
        },
    },
    {
        // Module files (ESM)
        files: [
            "js/legacy/modules/**/*.js",
            "js/legacy/modules/**/*.mjs",
            "js/legacy/*-loader.js",
            "js/legacy/*-loader.mjs",
            "js/legacy/*-init.mjs",
            "js/legacy/game-form-lookups.js",
        ],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                $: "readonly",
                jQuery: "readonly",
                navigator: "readonly",
                fetch: "readonly",
                URL: "readonly",
                caches: "readonly",
                self: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                Promise: "readonly",
                AbortController: "readonly",
                bootstrap: "readonly",
                XMLHttpRequest: "readonly",
                FormData: "readonly",
                CustomEvent: "readonly",
            },
        },
    },
    {
        // CommonJS and other script-like module files
        files: ["js/legacy/modules/**/*.cjs", "js/legacy/**/*.cjs"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "script",
            globals: {
                window: "readonly",
                document: "readonly",
                console: "readonly",
                module: "readonly",
                global: "readonly",
                $: "readonly",
                jQuery: "readonly",
            },
        },
    },
    {
        files: ["js/tests/**/*.js", "js/tests/**/*.mjs"],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                describe: "readonly",
                it: "readonly",
                test: "readonly",
                expect: "readonly",
                beforeEach: "readonly",
                afterEach: "readonly",
                beforeAll: "readonly",
                afterAll: "readonly",
                spyOn: "readonly",
                sinon: "readonly",
                jest: "readonly",
                require: "readonly",
                global: "readonly",
                exports: "readonly",
                Event: "readonly",
                HTMLFormElement: "readonly",
                MouseEvent: "readonly",
                KeyboardEvent: "readonly",
                document: "readonly",
                window: "readonly",
                $: "readonly",
                jQuery: "readonly",
                DataTable: "readonly",
                HTMLElement: "readonly",
                __dirname: "readonly",
                __filename: "readonly",
                module: "readonly",
                process: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                Promise: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                fetch: "readonly",
                FormData: "readonly",
                Blob: "readonly",
                File: "readonly",
                MutationObserver: "readonly",
                navigator: "readonly",
                Node: "readonly",
                DOMException: "readonly",
                CustomEvent: "readonly",
            },
        },
        rules: {
            "no-redeclare": "off",
            "no-unused-vars": [
                "error",
                { varsIgnorePattern: "^_", argsIgnorePattern: "^_" },
            ],
        },
    },
    {
        // Playwright E2E test files
        files: [
            "e2e/**/*.js",
            "e2e/**/*.mjs",
            "e2e/**/*.spec.js",
            "e2e/**/*.test.js",
        ],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: "module",
            globals: {
                test: "readonly",
                expect: "readonly",
                describe: "readonly",
                beforeEach: "readonly",
                afterEach: "readonly",
                beforeAll: "readonly",
                afterAll: "readonly",
                // Browser globals used inside page.evaluate() callbacks
                window: "readonly",
                document: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                navigator: "readonly",
                console: "readonly",
                HTMLElement: "readonly",
                Promise: "readonly",
                URL: "readonly",
                getComputedStyle: "readonly",
            },
        },
    },
];
