-- Test database schema.
--
-- This file provides the minimum table definitions needed for tests

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  status VARCHAR(20) NOT NULL DEFAULT 'inactive',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Site options table
CREATE TABLE IF NOT EXISTS site_options (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  option_key VARCHAR(50) NOT NULL UNIQUE,
  value TEXT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sports table
CREATE TABLE IF NOT EXISTS sports (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  sport_name VARCHAR(100) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Teams table
CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  sport_id INTEGER NOT NULL,
  team_name VARCHAR(100) NOT NULL,
  team_description TEXT NULL,
  abbr VARCHAR(10) NULL,
  gender VARCHAR(10) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Game EAV table
CREATE TABLE IF NOT EXISTS game_eav (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  key VARCHAR(100) NOT NULL,
  value TEXT NULL
);

-- Games table
CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  team_season_id INTEGER NOT NULL,
  game_date DATE NOT NULL,
  game_time TIME NULL,
  game_duration VARCHAR(10) NULL,
  game_type_id INTEGER NOT NULL,
  opponent_id INTEGER NOT NULL,
  place_id INTEGER NOT NULL,
  site_id INTEGER NOT NULL,
  hrn BOOLEAN DEFAULT 0,
  post BOOLEAN DEFAULT 0,
  w VARCHAR(1) NULL,
  l VARCHAR(1) NULL,
  pts_mur VARCHAR(3) NULL,
  pts_opp VARCHAR(3) NULL,
  mur_rk INTEGER NULL,
  opp_rk INTEGER NULL,
  periods VARCHAR(2) NULL
);

-- Team season roster table
CREATE TABLE IF NOT EXISTS team_season_roster (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  team_season_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  roster_year VARCHAR(4) NULL,
  roster_number VARCHAR(3) NULL,
  roster_position VARCHAR(30) NULL,
  roster_height VARCHAR(5) NULL,
  roster_weight VARCHAR(5) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sport configs table
CREATE TABLE IF NOT EXISTS sport_configs (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  sport_id INTEGER NOT NULL,
  config_key VARCHAR(50) NOT NULL,
  config_value TEXT NULL,
  description VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seasons table
CREATE TABLE IF NOT EXISTS seasons (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Places table
CREATE TABLE IF NOT EXISTS places (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  place_name VARCHAR(255) NOT NULL,
  place_city VARCHAR(100) NOT NULL,
  place_state VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sites table
CREATE TABLE IF NOT EXISTS sites (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  site_name VARCHAR(255) NOT NULL,
  place_id INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Persons table
CREATE TABLE IF NOT EXISTS persons (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  first VARCHAR(100) NOT NULL,
  last VARCHAR(100) NOT NULL,
  full VARCHAR(200) NOT NULL,
  display VARCHAR(200) NOT NULL,
  birth DATE NULL,
  death DATE NULL,
  person_image INTEGER NULL,
  bio TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Images table
CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  filename VARCHAR(255) NOT NULL,
  storage_subdir VARCHAR(255) NOT NULL,
  storage_path VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime VARCHAR(100) NOT NULL,
  ext VARCHAR(10) NOT NULL,
  byte_size INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  variants TEXT NOT NULL,
  hash VARCHAR(40) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sport stat registry table
CREATE TABLE IF NOT EXISTS sport_stat_registry (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  sport_id INTEGER NOT NULL,
  context VARCHAR(20) NOT NULL,
  entity_type VARCHAR(20) NOT NULL,
  table_name VARCHAR(100) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  field_mapping TEXT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Team season table
CREATE TABLE IF NOT EXISTS team_season (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  team_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  semester VARCHAR(10) NULL,
  team_season_image VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Game types table
CREATE TABLE IF NOT EXISTS game_types (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_type_name VARCHAR(100) NOT NULL,
  post BOOLEAN NOT NULL DEFAULT 0,
  conf BOOLEAN NOT NULL DEFAULT 0,
  ind VARCHAR(10) NULL
);

-- Opponents table
CREATE TABLE IF NOT EXISTS opponents (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  opponent_name VARCHAR(255) NOT NULL,
  place_id INTEGER NOT NULL,
  opponent_current VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
