-- Test database schema.
--
-- This file provides the minimum table definitions needed for tests

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  first_name VARCHAR(50) NULL,
  last_name VARCHAR(50) NULL,
  password VARCHAR(255) NOT NULL,
  token VARCHAR(255) NULL,
  token_expires DATETIME NULL,
  api_token VARCHAR(255) NULL,
  activation_date DATETIME NULL,
  tos_date DATETIME NULL,
  active BOOLEAN NOT NULL DEFAULT 0,
  is_superuser BOOLEAN NOT NULL DEFAULT 0,
  secret VARCHAR(32) NULL,
  secret_verified BOOLEAN NULL,
  additional_data TEXT NULL,
  last_login DATETIME NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'user',
  status VARCHAR(20) NOT NULL DEFAULT 'inactive',
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Site options table
CREATE TABLE IF NOT EXISTS site_options (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  option_key VARCHAR(50) NOT NULL UNIQUE,
  value TEXT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sports table
CREATE TABLE IF NOT EXISTS sports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sport_name VARCHAR(100) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Teams table
CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sport_id INTEGER NOT NULL,
  team_name VARCHAR(100) NOT NULL,
  team_description TEXT NULL,
  abbr VARCHAR(10) NULL,
  gender VARCHAR(10) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Game EAV table
CREATE TABLE IF NOT EXISTS game_eav (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NOT NULL,
  key VARCHAR(100) NOT NULL,
  value TEXT NULL
);

-- Games table
CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_id INTEGER NOT NULL,
  game_date DATE NOT NULL,
  game_time TIME NULL,
  game_duration VARCHAR(10) NULL,
  game_type_id INTEGER NOT NULL,
  opponent_id INTEGER NOT NULL,
  place_id INTEGER NOT NULL,
  site_id INTEGER NOT NULL,
  hrn INTEGER DEFAULT 0,
  post BOOLEAN DEFAULT 0,
  w VARCHAR(1) NULL,
  l VARCHAR(1) NULL,
  pts_mur VARCHAR(3) NULL,
  pts_opp VARCHAR(3) NULL,
  mur_rk INTEGER NULL,
  opp_rk INTEGER NULL,
  periods VARCHAR(2) NULL
);

-- Team season roster table
CREATE TABLE IF NOT EXISTS team_season_roster (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  roster_year VARCHAR(4) NULL,
  roster_number VARCHAR(3) NULL,
  roster_position VARCHAR(30) NULL,
  roster_height VARCHAR(5) NULL,
  roster_weight VARCHAR(5) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sport configs table
CREATE TABLE IF NOT EXISTS sport_configs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sport_id INTEGER NOT NULL,
  config_key VARCHAR(50) NOT NULL,
  config_value TEXT NULL,
  description VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seasons table
CREATE TABLE IF NOT EXISTS seasons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Places table
CREATE TABLE IF NOT EXISTS places (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  place_name VARCHAR(255) NOT NULL,
  place_state VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sites table
CREATE TABLE IF NOT EXISTS sites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  site_name VARCHAR(255) NOT NULL,
  place_id INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Persons table
CREATE TABLE IF NOT EXISTS persons (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first VARCHAR(100) NOT NULL,
  last VARCHAR(100) NOT NULL,
  full VARCHAR(200) NOT NULL,
  display VARCHAR(200) NOT NULL,
  birth DATE NULL,
  death DATE NULL,
  person_image INTEGER NULL,
  bio TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Images table
CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename VARCHAR(255) NOT NULL,
  storage_subdir VARCHAR(255) NOT NULL,
  storage_path VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  mime VARCHAR(100) NOT NULL,
  ext VARCHAR(10) NOT NULL,
  byte_size INTEGER NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  variants TEXT NOT NULL,
  hash VARCHAR(40) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Sport stat registry table
CREATE TABLE IF NOT EXISTS sport_stat_registry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sport_id INTEGER NOT NULL,
  context VARCHAR(20) NOT NULL,
  entity_type VARCHAR(20) NOT NULL,
  table_name VARCHAR(100) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  field_mapping TEXT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Team season table
CREATE TABLE IF NOT EXISTS team_season (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id INTEGER NOT NULL,
  season_id INTEGER NOT NULL,
  semester VARCHAR(10) NULL,
  team_season_image VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Game types table
CREATE TABLE IF NOT EXISTS game_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_type_name VARCHAR(100) NOT NULL,
  post BOOLEAN NOT NULL DEFAULT 0,
  conf BOOLEAN NOT NULL DEFAULT 0,
  ind VARCHAR(10) NULL
);

-- Opponents table
CREATE TABLE IF NOT EXISTS opponents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  opponent_name VARCHAR(255) NOT NULL,
  place_id INTEGER NOT NULL,
  opponent_current VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Basketball game statistics tables
CREATE TABLE IF NOT EXISTS stat_basket_game_person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_roster_id INTEGER NULL,
  game_id INTEGER NULL,
  period VARCHAR(10) NULL,
  GP VARCHAR(1) NULL,
  GS VARCHAR(1) NULL,
  MIN VARCHAR(3) NULL,
  FGM VARCHAR(2) NULL,
  FGA VARCHAR(3) NULL,
  TPM VARCHAR(2) NULL,
  TPA VARCHAR(2) NULL,
  FTM VARCHAR(2) NULL,
  FTA VARCHAR(2) NULL,
  ORB VARCHAR(2) NULL,
  DRB VARCHAR(2) NULL,
  RB VARCHAR(2) NULL,
  AST VARCHAR(2) NULL,
  STL VARCHAR(2) NULL,
  BS VARCHAR(2) NULL,
  BD VARCHAR(2) NULL,
  TRN VARCHAR(2) NULL,
  PF VARCHAR(1) NULL,
  TF VARCHAR(1) NULL,
  FD VARCHAR(1) NULL,
  PTS VARCHAR(3) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stat_basket_game_opponent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NULL,
  period VARCHAR(10) NULL,
  name VARCHAR(162) NULL,
  jersey VARCHAR(11) NULL,
  position VARCHAR(11) NULL,
  GP VARCHAR(1) NULL,
  GS VARCHAR(1) NULL,
  MIN VARCHAR(3) NULL,
  FGM VARCHAR(2) NULL,
  FGA VARCHAR(3) NULL,
  TPM VARCHAR(2) NULL,
  TPA VARCHAR(2) NULL,
  FTM VARCHAR(2) NULL,
  FTA VARCHAR(2) NULL,
  ORB VARCHAR(2) NULL,
  DRB VARCHAR(2) NULL,
  RB VARCHAR(2) NULL,
  AST VARCHAR(2) NULL,
  STL VARCHAR(2) NULL,
  BS VARCHAR(2) NULL,
  BD VARCHAR(2) NULL,
  TRN VARCHAR(2) NULL,
  PF VARCHAR(1) NULL,
  TF VARCHAR(1) NULL,
  FD VARCHAR(1) NULL,
  PTS VARCHAR(3) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stat_basket_game_team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NULL,
  opp TINYINT NULL,
  ORB VARCHAR(11) NULL,
  DRB VARCHAR(11) NULL,
  RB VARCHAR(11) NULL,
  TRN VARCHAR(11) NULL,
  TF VARCHAR(11) NULL,
  PTS VARCHAR(11) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Basketball game stats: Box scores (period and final stats)
CREATE TABLE IF NOT EXISTS stat_basket_game_box (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER NULL,
  opponent_id INTEGER NULL,
  period VARCHAR(10) NULL,
  FGM VARCHAR(11) NULL,
  FGA VARCHAR(11) NULL,
  TPM VARCHAR(11) NULL,
  TPA VARCHAR(11) NULL,
  FTM VARCHAR(11) NULL,
  FTA VARCHAR(11) NULL,
  ORB VARCHAR(11) NULL,
  DRB VARCHAR(11) NULL,
  RB VARCHAR(11) NULL,
  AST VARCHAR(11) NULL,
  STL VARCHAR(11) NULL,
  BS VARCHAR(11) NULL,
  TRN VARCHAR(11) NULL,
  PF VARCHAR(11) NULL,
  TF VARCHAR(11) NULL,
  PTS VARCHAR(11) NULL,
  PNT VARCHAR(11) NULL,
  OTO VARCHAR(11) NULL,
  SND VARCHAR(11) NULL,
  FB VARCHAR(11) NULL,
  BN VARCHAR(11) NULL,
  TIED VARCHAR(11) NULL,
  LC VARCHAR(11) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Basketball season stats: Player stats
CREATE TABLE IF NOT EXISTS stat_basket_season_person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_roster_id INTEGER NULL,
  GP VARCHAR(11) NULL,
  GS VARCHAR(11) NULL,
  MIN VARCHAR(11) NULL,
  FGM VARCHAR(11) NULL,
  FGA VARCHAR(11) NULL,
  TPM VARCHAR(11) NULL,
  TPA VARCHAR(11) NULL,
  FTM VARCHAR(11) NULL,
  FTA VARCHAR(11) NULL,
  ORB VARCHAR(11) NULL,
  DRB VARCHAR(11) NULL,
  RB VARCHAR(11) NULL,
  AST VARCHAR(11) NULL,
  STL VARCHAR(11) NULL,
  BS VARCHAR(11) NULL,
  TRN VARCHAR(11) NULL,
  PF VARCHAR(11) NULL,
  TF VARCHAR(11) NULL,
  PTS INTEGER NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Basketball season stats: Team stats
CREATE TABLE IF NOT EXISTS stat_basket_season_team (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_id INTEGER NULL,
  GP VARCHAR(11) NULL,
  MIN VARCHAR(11) NULL,
  FGM VARCHAR(11) NULL,
  FGA VARCHAR(11) NULL,
  TPM VARCHAR(11) NULL,
  TPA VARCHAR(11) NULL,
  FTM VARCHAR(11) NULL,
  FTA VARCHAR(11) NULL,
  ORB VARCHAR(11) NULL,
  DRB VARCHAR(11) NULL,
  RB VARCHAR(11) NULL,
  AST VARCHAR(11) NULL,
  STL VARCHAR(11) NULL,
  BS VARCHAR(11) NULL,
  TRN VARCHAR(11) NULL,
  PF VARCHAR(11) NULL,
  TF VARCHAR(11) NULL,
  PTS VARCHAR(11) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Basketball season stats: Opponent stats
CREATE TABLE IF NOT EXISTS stat_basket_season_opponent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_season_id INTEGER NULL,
  GP VARCHAR(11) NULL,
  MIN VARCHAR(11) NULL,
  FGM VARCHAR(11) NULL,
  FGA VARCHAR(11) NULL,
  TPM VARCHAR(11) NULL,
  TPA VARCHAR(11) NULL,
  FTM VARCHAR(11) NULL,
  FTA VARCHAR(11) NULL,
  ORB VARCHAR(11) NULL,
  DRB VARCHAR(11) NULL,
  RB VARCHAR(11) NULL,
  AST VARCHAR(11) NULL,
  STL VARCHAR(11) NULL,
  BS VARCHAR(11) NULL,
  TRN VARCHAR(11) NULL,
  PF VARCHAR(11) NULL,
  TF VARCHAR(11) NULL,
  PTS VARCHAR(11) NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Image Tags table
CREATE TABLE IF NOT EXISTS image_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Images/ImageTags junction table (many-to-many)
CREATE TABLE IF NOT EXISTS images_image_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image_id INTEGER NOT NULL,
  image_tag_id INTEGER NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(image_id, image_tag_id),
  FOREIGN KEY(image_id) REFERENCES images(id),
  FOREIGN KEY(image_tag_id) REFERENCES image_tags(id)
);

-- Blog tables
CREATE TABLE IF NOT EXISTS blog_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(190) NOT NULL,
  slug VARCHAR(190) NOT NULL UNIQUE,
  excerpt TEXT NULL,
  body TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  is_published BOOLEAN NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  hero_image_id INTEGER NULL,
  created DATETIME NULL,
  modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS blog_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  created DATETIME NULL,
  modified DATETIME NULL
);

CREATE TABLE IF NOT EXISTS blog_posts_blog_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  blog_post_id INTEGER NOT NULL,
  blog_tag_id INTEGER NOT NULL,
  created DATETIME NULL,
  modified DATETIME NULL,
  FOREIGN KEY(blog_post_id) REFERENCES blog_posts(id),
  FOREIGN KEY(blog_tag_id) REFERENCES blog_tags(id)
);
